# Generated by Django 4.0.3 on 2022-03-07 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_postgres_exercise_1', '0002_locations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
    ]
