# Generated by Django 4.0.3 on 2022-03-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_postgres_exercise_1', '0003_rename_countries_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='region_id',
            new_name='region',
        ),
    ]
