# Generated by Django 4.0.3 on 2022-03-07 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_postgres_exercise_1', '0004_rename_region_id_country_region'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
    ]
