# Generated by Django 4.0.3 on 2022-03-07 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_postgres_exercise_1', '0005_rename_locations_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='country_id',
            new_name='country',
        ),
    ]
